### ISSUE TITLE
Problem with New Version (0.1.3)

### ISSUE THREAD

**Issue by elderni** [huangyh09/cellSNP#2]
I updated cellSNP yesterday and found that data that had previously worked with the tool no longer did. I also tested the data used in your test.sh file and got the same traceback. Here is an example of the output: 

[cellSNP] mode 2: pileup 22 whole chromosomes in 4246 single cells.
Traceback (most recent call last):
  File "/home/rstudio/.local/bin/cellSNP", line 11, in <module>
    sys.exit(main())
  File "/home/rstudio/.local/lib/python2.7/site-packages/cellSNP/cellSNP.py", line 198, in main
    result = [res.get() if nproc > 1 else res for res in result]
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
RuntimeWarning: divide by zero encountered in log

I ultimately uninstalled cellSNP and reinstalled version 0.0.8 and found that it works just fine again. I'm still not sure what caused the issue in the newer version but wanted to alert you to it.

**Comment by huangyh09** [comment]
Hi, it looks that you are using python 2.7. Could you try it with Python 3. I haven't tested the new versions under Python 2.

Also, cellSNP (>=0.1.0) requires pysam>=0.15.2. Not sure which causes the issue, but your feedback will appreciated.

**Comment by elderni** [comment]
That solved the problem! Thank you.
