### ISSUE TITLE
Run time estimation

### ISSUE THREAD

**Issue by coh-racng** [huangyh09/cellSNP#3]
How long would it approximately take to run cellSNP (Mode 1 with region_vcf) on HiSeq data with ~200M reads and 4000 cells?
Do you have some examples of cellSNP runtimes for some number of cells, number of reads, and number of subprocesses (-p option)?

**Comment by huangyh09** [comment]
Hi, I would expect less than 20 hours with around 20 CPUs for genotyping ~10M candiate SNPs in your case. The running time is roughly linear to the number of reads and the candidate SNPs.

We may have a guideline in near future. Thanks.
